# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/david/Documents/pico-lcd/libs/lcd/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/david/pico/pico-sdk/pico_sdk_init.cmake))

/Users/david/Documents/pico-lcd/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.25.1/bin/cmake -H/Users/david/Documents/pico-lcd -B/Users/david/Documents/pico-lcd
